export default JourneySchema = {
  name: "Journey",
  primaryKey: "id",
  properties: {
    id: { type: "int", indexed: true },
    operator: "string",
    dateStart: "date",
    dateFinish: "date?",
    veicule_id:"int",
    kmInicial:'string',
    kmFinal:'string?',
    latitudeInicial:'string',
    latitudeFinal:'string?',
    longitudeInicial:'string',
    longitudeFinal:'string?',
    check:{ type: "bool",optional:true},
    systemUnitId:'string',
    systemUserId:'string',
    occurrences: "Occurrence[]",
  },
};
