export default JourneySchema = {
  name: "Journey",
  primaryKey: "id",
  properties: {
    id: { type: "int", indexed: true },
    operator_id:'int',
    operator: "string",
    dateStart: "date",
    dateFinish: "date?",
    veicule_id:"int",
    veicule_name:'string',
    kmInicial:'string',
    kmFinal:'string?',
    latitudeInicial:'string',
    latitudeFinal:'string?',
    longitudeInicial:'string',
    longitudeFinal:'string?',
    check:{ type: "bool",optional:true},
    systemUnitId:'int',
    systemUserId:'int',
    occurrences: "OccurrenceList[]",
  },
};
